### ISSUE TITLE
Plots: implement dotplot

### ISSUE THREAD

**Issue by alona-sydorova** [collinleiber/benchmarkVis#18]

**Comment by alona-sydorova** [comment]
scatter plot

**Comment by alona-sydorova** [comment]
x and y are 2 different measures, and points' color depends on both algorithm and problem.

**Comment by collinleiber** [comment]
Compare: createIterationDualParameterPlot(mlr.tuning.example, "measure.acc.test.mean", "C", "sigma")

But don't use different sizes for the points

**Comment by alona-sydorova** [comment]
@likunlan you have already implemented it and no further to-do's regarding scatter plot are left, so we can close the issue, right?
