### ISSUE TITLE
Plot ideas

### ISSUE THREAD

**Issue by collinleiber** [collinleiber/benchmarkVis#23]
- [x]  Parallel Coordinates Plot
- [x]  Scatter Matrix
- [x]  Star Plot

**Comment by alona-sydorova** [comment]
Scatter matrix:
https://mlr-org.github.io/mlr-tutorial/release/html/benchmark_experiments/index.html#benchmark-analysis-and-visualization
https://www.rdocumentation.org/packages/GGally/versions/1.3.2/topics/ggpairs
