### ISSUE TITLE
SHINY

### ISSUE THREAD

**Issue by alona-sydorova** [collinleiber/benchmarkVis#33]
- [x] tabübergreifende Auswahl orig/aggr data
- [x] neue Plots integrieren
- [x] DT tab -> Transformation nach rechts 
- [x] Rank tab -> Auswahl löschen
- [x] import tab -> Spaltenauswahl weg

- [x] plot tab : parameter für plots dynamisch
- [x] plot tab :  list of plots abhängig von import 
- [x]  plot tab: new tab name field -> tab name entspr.
- [x] plot : Tab Auswahl dynamisch erstellen und löschen

- [x] Reset von data file

- [x] adjust for radar plot (see comments)

**Comment by collinleiber** [comment]
radar plot for shiny:
take a look at: https://github.com/MangoTheCat/radarchart
